services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    networks:
      - default_network
    ports:
      - 15672:15672
    environment:
      RABBITMQ_MANAGEMENT_AGENT_DISABLE_METRICS_COLLECTOR: 'false'
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      - ~/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

  synapse:
    container_name: synapse
    networks:
      - default_network
    build:
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - 5174:8080
      - 5173:80
    environment:
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

networks:
  default_network:

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
