services:
  # node_server:
  #   build: ./server
  #   container_name: server_app
  #   ports:
  #     - "5174:5174"
  #   networks:
  #     - app_network

  # node_client:
  #   build: ./web
  #   container_name: client_app
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - app_network

  #   depends_on:
  #     - node_server
  redis:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "6379:6380"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge