services:
  redis_service:
    image: redis
    container_name: redis_service
    ports:
      - "6379:6379"

  # server_app:
  #   build: ./server
  #   container_name: server_app
  #   ports:
  #     - "5174:5174"
  #   depends_on:
  #     - redis_service

  # client_app:
  #   build: ./web
  #   container_name: client_app
  #   ports:
  #     - "5173:5173"

    # depends_on:
    #   - server_app